# coding: utf-8

"""
    IncQuery Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class IndexCompartment(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'model_compartment': 'ModelCompartment',
        'indexes': 'list[Index]'
    }

    attribute_map = {
        'model_compartment': 'modelCompartment',
        'indexes': 'indexes'
    }

    def __init__(self, model_compartment=None, indexes=None):  # noqa: E501
        """IndexCompartment - a model defined in OpenAPI"""  # noqa: E501

        self._model_compartment = None
        self._indexes = None
        self.discriminator = None

        if model_compartment is not None:
            self.model_compartment = model_compartment
        if indexes is not None:
            self.indexes = indexes

    @property
    def model_compartment(self):
        """Gets the model_compartment of this IndexCompartment.  # noqa: E501


        :return: The model_compartment of this IndexCompartment.  # noqa: E501
        :rtype: ModelCompartment
        """
        return self._model_compartment

    @model_compartment.setter
    def model_compartment(self, model_compartment):
        """Sets the model_compartment of this IndexCompartment.


        :param model_compartment: The model_compartment of this IndexCompartment.  # noqa: E501
        :type: ModelCompartment
        """

        self._model_compartment = model_compartment

    @property
    def indexes(self):
        """Gets the indexes of this IndexCompartment.  # noqa: E501


        :return: The indexes of this IndexCompartment.  # noqa: E501
        :rtype: list[Index]
        """
        return self._indexes

    @indexes.setter
    def indexes(self, indexes):
        """Sets the indexes of this IndexCompartment.


        :param indexes: The indexes of this IndexCompartment.  # noqa: E501
        :type: list[Index]
        """

        self._indexes = indexes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IndexCompartment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
