# coding: utf-8

"""
    IncQuery Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class MMSProject(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'project_id': 'str',
        'name': 'str',
        'refs': 'list[MMSRef]'
    }

    attribute_map = {
        'project_id': 'projectId',
        'name': 'name',
        'refs': 'refs'
    }

    def __init__(self, project_id=None, name=None, refs=None):  # noqa: E501
        """MMSProject - a model defined in OpenAPI"""  # noqa: E501

        self._project_id = None
        self._name = None
        self._refs = None
        self.discriminator = None

        self.project_id = project_id
        if name is not None:
            self.name = name
        self.refs = refs

    @property
    def project_id(self):
        """Gets the project_id of this MMSProject.  # noqa: E501


        :return: The project_id of this MMSProject.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this MMSProject.


        :param project_id: The project_id of this MMSProject.  # noqa: E501
        :type: str
        """
        if project_id is None:
            raise ValueError("Invalid value for `project_id`, must not be `None`")  # noqa: E501

        self._project_id = project_id

    @property
    def name(self):
        """Gets the name of this MMSProject.  # noqa: E501


        :return: The name of this MMSProject.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MMSProject.


        :param name: The name of this MMSProject.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def refs(self):
        """Gets the refs of this MMSProject.  # noqa: E501


        :return: The refs of this MMSProject.  # noqa: E501
        :rtype: list[MMSRef]
        """
        return self._refs

    @refs.setter
    def refs(self, refs):
        """Sets the refs of this MMSProject.


        :param refs: The refs of this MMSProject.  # noqa: E501
        :type: list[MMSRef]
        """
        if refs is None:
            raise ValueError("Invalid value for `refs`, must not be `None`")  # noqa: E501

        self._refs = refs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MMSProject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
