# coding: utf-8

"""
    IncQuery Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class MMSCommitDetails(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'organization_name': 'str',
        'project_name': 'str',
        'ref_name': 'str',
        'commit_name': 'str',
        'author': 'str'
    }

    attribute_map = {
        'organization_name': 'organizationName',
        'project_name': 'projectName',
        'ref_name': 'refName',
        'commit_name': 'commitName',
        'author': 'author'
    }

    def __init__(self, organization_name=None, project_name=None, ref_name=None, commit_name=None, author=None):  # noqa: E501
        """MMSCommitDetails - a model defined in OpenAPI"""  # noqa: E501

        self._organization_name = None
        self._project_name = None
        self._ref_name = None
        self._commit_name = None
        self._author = None
        self.discriminator = None

        self.organization_name = organization_name
        self.project_name = project_name
        self.ref_name = ref_name
        self.commit_name = commit_name
        self.author = author

    @property
    def organization_name(self):
        """Gets the organization_name of this MMSCommitDetails.  # noqa: E501


        :return: The organization_name of this MMSCommitDetails.  # noqa: E501
        :rtype: str
        """
        return self._organization_name

    @organization_name.setter
    def organization_name(self, organization_name):
        """Sets the organization_name of this MMSCommitDetails.


        :param organization_name: The organization_name of this MMSCommitDetails.  # noqa: E501
        :type: str
        """
        if organization_name is None:
            raise ValueError("Invalid value for `organization_name`, must not be `None`")  # noqa: E501

        self._organization_name = organization_name

    @property
    def project_name(self):
        """Gets the project_name of this MMSCommitDetails.  # noqa: E501


        :return: The project_name of this MMSCommitDetails.  # noqa: E501
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name):
        """Sets the project_name of this MMSCommitDetails.


        :param project_name: The project_name of this MMSCommitDetails.  # noqa: E501
        :type: str
        """
        if project_name is None:
            raise ValueError("Invalid value for `project_name`, must not be `None`")  # noqa: E501

        self._project_name = project_name

    @property
    def ref_name(self):
        """Gets the ref_name of this MMSCommitDetails.  # noqa: E501


        :return: The ref_name of this MMSCommitDetails.  # noqa: E501
        :rtype: str
        """
        return self._ref_name

    @ref_name.setter
    def ref_name(self, ref_name):
        """Sets the ref_name of this MMSCommitDetails.


        :param ref_name: The ref_name of this MMSCommitDetails.  # noqa: E501
        :type: str
        """
        if ref_name is None:
            raise ValueError("Invalid value for `ref_name`, must not be `None`")  # noqa: E501

        self._ref_name = ref_name

    @property
    def commit_name(self):
        """Gets the commit_name of this MMSCommitDetails.  # noqa: E501


        :return: The commit_name of this MMSCommitDetails.  # noqa: E501
        :rtype: str
        """
        return self._commit_name

    @commit_name.setter
    def commit_name(self, commit_name):
        """Sets the commit_name of this MMSCommitDetails.


        :param commit_name: The commit_name of this MMSCommitDetails.  # noqa: E501
        :type: str
        """
        if commit_name is None:
            raise ValueError("Invalid value for `commit_name`, must not be `None`")  # noqa: E501

        self._commit_name = commit_name

    @property
    def author(self):
        """Gets the author of this MMSCommitDetails.  # noqa: E501


        :return: The author of this MMSCommitDetails.  # noqa: E501
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author):
        """Sets the author of this MMSCommitDetails.


        :param author: The author of this MMSCommitDetails.  # noqa: E501
        :type: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MMSCommitDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
