# coding: utf-8

"""
    IncQuery Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class MMSRef(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ref_id': 'str',
        'name': 'str',
        'commits': 'list[object]'
    }

    attribute_map = {
        'ref_id': 'refId',
        'name': 'name',
        'commits': 'commits'
    }

    def __init__(self, ref_id=None, name=None, commits=None):  # noqa: E501
        """MMSRef - a model defined in OpenAPI"""  # noqa: E501

        self._ref_id = None
        self._name = None
        self._commits = None
        self.discriminator = None

        self.ref_id = ref_id
        if name is not None:
            self.name = name
        self.commits = commits

    @property
    def ref_id(self):
        """Gets the ref_id of this MMSRef.  # noqa: E501


        :return: The ref_id of this MMSRef.  # noqa: E501
        :rtype: str
        """
        return self._ref_id

    @ref_id.setter
    def ref_id(self, ref_id):
        """Sets the ref_id of this MMSRef.


        :param ref_id: The ref_id of this MMSRef.  # noqa: E501
        :type: str
        """
        if ref_id is None:
            raise ValueError("Invalid value for `ref_id`, must not be `None`")  # noqa: E501

        self._ref_id = ref_id

    @property
    def name(self):
        """Gets the name of this MMSRef.  # noqa: E501


        :return: The name of this MMSRef.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MMSRef.


        :param name: The name of this MMSRef.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def commits(self):
        """Gets the commits of this MMSRef.  # noqa: E501


        :return: The commits of this MMSRef.  # noqa: E501
        :rtype: list[object]
        """
        return self._commits

    @commits.setter
    def commits(self, commits):
        """Sets the commits of this MMSRef.


        :param commits: The commits of this MMSRef.  # noqa: E501
        :type: list[object]
        """
        if commits is None:
            raise ValueError("Invalid value for `commits`, must not be `None`")  # noqa: E501

        self._commits = commits

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MMSRef):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
