# coding: utf-8

"""
    IncQuery Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class MMSCommitDescriptor(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'org_id': 'str',
        'project_id': 'str',
        'ref_id': 'str',
        'commit_id': 'str',
        'name': 'str',
        'compartment_uri': 'str',
        'author': 'str'
    }

    attribute_map = {
        'org_id': 'orgId',
        'project_id': 'projectId',
        'ref_id': 'refId',
        'commit_id': 'commitId',
        'name': 'name',
        'compartment_uri': 'compartmentURI',
        'author': 'author'
    }

    def __init__(self, org_id=None, project_id=None, ref_id=None, commit_id=None, name=None, compartment_uri=None, author=None):  # noqa: E501
        """MMSCommitDescriptor - a model defined in OpenAPI"""  # noqa: E501

        self._org_id = None
        self._project_id = None
        self._ref_id = None
        self._commit_id = None
        self._name = None
        self._compartment_uri = None
        self._author = None
        self.discriminator = None

        self.org_id = org_id
        self.project_id = project_id
        self.ref_id = ref_id
        self.commit_id = commit_id
        if name is not None:
            self.name = name
        self.compartment_uri = compartment_uri
        if author is not None:
            self.author = author

    @property
    def org_id(self):
        """Gets the org_id of this MMSCommitDescriptor.  # noqa: E501


        :return: The org_id of this MMSCommitDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this MMSCommitDescriptor.


        :param org_id: The org_id of this MMSCommitDescriptor.  # noqa: E501
        :type: str
        """
        if org_id is None:
            raise ValueError("Invalid value for `org_id`, must not be `None`")  # noqa: E501

        self._org_id = org_id

    @property
    def project_id(self):
        """Gets the project_id of this MMSCommitDescriptor.  # noqa: E501


        :return: The project_id of this MMSCommitDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this MMSCommitDescriptor.


        :param project_id: The project_id of this MMSCommitDescriptor.  # noqa: E501
        :type: str
        """
        if project_id is None:
            raise ValueError("Invalid value for `project_id`, must not be `None`")  # noqa: E501

        self._project_id = project_id

    @property
    def ref_id(self):
        """Gets the ref_id of this MMSCommitDescriptor.  # noqa: E501


        :return: The ref_id of this MMSCommitDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._ref_id

    @ref_id.setter
    def ref_id(self, ref_id):
        """Sets the ref_id of this MMSCommitDescriptor.


        :param ref_id: The ref_id of this MMSCommitDescriptor.  # noqa: E501
        :type: str
        """
        if ref_id is None:
            raise ValueError("Invalid value for `ref_id`, must not be `None`")  # noqa: E501

        self._ref_id = ref_id

    @property
    def commit_id(self):
        """Gets the commit_id of this MMSCommitDescriptor.  # noqa: E501


        :return: The commit_id of this MMSCommitDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._commit_id

    @commit_id.setter
    def commit_id(self, commit_id):
        """Sets the commit_id of this MMSCommitDescriptor.


        :param commit_id: The commit_id of this MMSCommitDescriptor.  # noqa: E501
        :type: str
        """
        if commit_id is None:
            raise ValueError("Invalid value for `commit_id`, must not be `None`")  # noqa: E501

        self._commit_id = commit_id

    @property
    def name(self):
        """Gets the name of this MMSCommitDescriptor.  # noqa: E501


        :return: The name of this MMSCommitDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MMSCommitDescriptor.


        :param name: The name of this MMSCommitDescriptor.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def compartment_uri(self):
        """Gets the compartment_uri of this MMSCommitDescriptor.  # noqa: E501


        :return: The compartment_uri of this MMSCommitDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._compartment_uri

    @compartment_uri.setter
    def compartment_uri(self, compartment_uri):
        """Sets the compartment_uri of this MMSCommitDescriptor.


        :param compartment_uri: The compartment_uri of this MMSCommitDescriptor.  # noqa: E501
        :type: str
        """
        if compartment_uri is None:
            raise ValueError("Invalid value for `compartment_uri`, must not be `None`")  # noqa: E501

        self._compartment_uri = compartment_uri

    @property
    def author(self):
        """Gets the author of this MMSCommitDescriptor.  # noqa: E501


        :return: The author of this MMSCommitDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author):
        """Sets the author of this MMSCommitDescriptor.


        :param author: The author of this MMSCommitDescriptor.  # noqa: E501
        :type: str
        """

        self._author = author

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MMSCommitDescriptor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
