# coding: utf-8

"""
    IncQuery Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class QueryParameter(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'parameter_name': 'str',
        'parameter_type': 'str'
    }

    attribute_map = {
        'parameter_name': 'parameterName',
        'parameter_type': 'parameterType'
    }

    def __init__(self, parameter_name=None, parameter_type=None):  # noqa: E501
        """QueryParameter - a model defined in OpenAPI"""  # noqa: E501

        self._parameter_name = None
        self._parameter_type = None
        self.discriminator = None

        self.parameter_name = parameter_name
        self.parameter_type = parameter_type

    @property
    def parameter_name(self):
        """Gets the parameter_name of this QueryParameter.  # noqa: E501


        :return: The parameter_name of this QueryParameter.  # noqa: E501
        :rtype: str
        """
        return self._parameter_name

    @parameter_name.setter
    def parameter_name(self, parameter_name):
        """Sets the parameter_name of this QueryParameter.


        :param parameter_name: The parameter_name of this QueryParameter.  # noqa: E501
        :type: str
        """
        if parameter_name is None:
            raise ValueError("Invalid value for `parameter_name`, must not be `None`")  # noqa: E501

        self._parameter_name = parameter_name

    @property
    def parameter_type(self):
        """Gets the parameter_type of this QueryParameter.  # noqa: E501


        :return: The parameter_type of this QueryParameter.  # noqa: E501
        :rtype: str
        """
        return self._parameter_type

    @parameter_type.setter
    def parameter_type(self, parameter_type):
        """Sets the parameter_type of this QueryParameter.


        :param parameter_type: The parameter_type of this QueryParameter.  # noqa: E501
        :type: str
        """
        if parameter_type is None:
            raise ValueError("Invalid value for `parameter_type`, must not be `None`")  # noqa: E501

        self._parameter_type = parameter_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QueryParameter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
