# coding: utf-8

"""
    IncQuery Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class RepositoryStructureResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'twc': 'list[TWCRepositoryStructure]',
        'mms': 'list[MMSRepositoryStructure]'
    }

    attribute_map = {
        'twc': 'twc',
        'mms': 'mms'
    }

    def __init__(self, twc=None, mms=None):  # noqa: E501
        """RepositoryStructureResponse - a model defined in OpenAPI"""  # noqa: E501

        self._twc = None
        self._mms = None
        self.discriminator = None

        if twc is not None:
            self.twc = twc
        if mms is not None:
            self.mms = mms

    @property
    def twc(self):
        """Gets the twc of this RepositoryStructureResponse.  # noqa: E501


        :return: The twc of this RepositoryStructureResponse.  # noqa: E501
        :rtype: list[TWCRepositoryStructure]
        """
        return self._twc

    @twc.setter
    def twc(self, twc):
        """Sets the twc of this RepositoryStructureResponse.


        :param twc: The twc of this RepositoryStructureResponse.  # noqa: E501
        :type: list[TWCRepositoryStructure]
        """

        self._twc = twc

    @property
    def mms(self):
        """Gets the mms of this RepositoryStructureResponse.  # noqa: E501


        :return: The mms of this RepositoryStructureResponse.  # noqa: E501
        :rtype: list[MMSRepositoryStructure]
        """
        return self._mms

    @mms.setter
    def mms(self, mms):
        """Sets the mms of this RepositoryStructureResponse.


        :param mms: The mms of this RepositoryStructureResponse.  # noqa: E501
        :type: list[MMSRepositoryStructure]
        """

        self._mms = mms

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RepositoryStructureResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
