# coding: utf-8

"""
    IncQuery Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Resource(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'resource_id': 'str',
        'title': 'str',
        'branches': 'list[Branch]'
    }

    attribute_map = {
        'resource_id': 'resourceId',
        'title': 'title',
        'branches': 'branches'
    }

    def __init__(self, resource_id=None, title=None, branches=None):  # noqa: E501
        """Resource - a model defined in OpenAPI"""  # noqa: E501

        self._resource_id = None
        self._title = None
        self._branches = None
        self.discriminator = None

        self.resource_id = resource_id
        if title is not None:
            self.title = title
        self.branches = branches

    @property
    def resource_id(self):
        """Gets the resource_id of this Resource.  # noqa: E501


        :return: The resource_id of this Resource.  # noqa: E501
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """Sets the resource_id of this Resource.


        :param resource_id: The resource_id of this Resource.  # noqa: E501
        :type: str
        """
        if resource_id is None:
            raise ValueError("Invalid value for `resource_id`, must not be `None`")  # noqa: E501

        self._resource_id = resource_id

    @property
    def title(self):
        """Gets the title of this Resource.  # noqa: E501


        :return: The title of this Resource.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Resource.


        :param title: The title of this Resource.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def branches(self):
        """Gets the branches of this Resource.  # noqa: E501


        :return: The branches of this Resource.  # noqa: E501
        :rtype: list[Branch]
        """
        return self._branches

    @branches.setter
    def branches(self, branches):
        """Sets the branches of this Resource.


        :param branches: The branches of this Resource.  # noqa: E501
        :type: list[Branch]
        """
        if branches is None:
            raise ValueError("Invalid value for `branches`, must not be `None`")  # noqa: E501

        self._branches = branches

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Resource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
