# coding: utf-8

"""
    IncQuery Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ServerStatusResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'up_time': 'str',
        'component_statuses': 'object',
        'server_status_message': 'ServerStatusMessage'
    }

    attribute_map = {
        'up_time': 'upTime',
        'component_statuses': 'componentStatuses',
        'server_status_message': 'serverStatusMessage'
    }

    def __init__(self, up_time=None, component_statuses=None, server_status_message=None):  # noqa: E501
        """ServerStatusResponse - a model defined in OpenAPI"""  # noqa: E501

        self._up_time = None
        self._component_statuses = None
        self._server_status_message = None
        self.discriminator = None

        self.up_time = up_time
        self.component_statuses = component_statuses
        self.server_status_message = server_status_message

    @property
    def up_time(self):
        """Gets the up_time of this ServerStatusResponse.  # noqa: E501


        :return: The up_time of this ServerStatusResponse.  # noqa: E501
        :rtype: str
        """
        return self._up_time

    @up_time.setter
    def up_time(self, up_time):
        """Sets the up_time of this ServerStatusResponse.


        :param up_time: The up_time of this ServerStatusResponse.  # noqa: E501
        :type: str
        """
        if up_time is None:
            raise ValueError("Invalid value for `up_time`, must not be `None`")  # noqa: E501

        self._up_time = up_time

    @property
    def component_statuses(self):
        """Gets the component_statuses of this ServerStatusResponse.  # noqa: E501


        :return: The component_statuses of this ServerStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._component_statuses

    @component_statuses.setter
    def component_statuses(self, component_statuses):
        """Sets the component_statuses of this ServerStatusResponse.


        :param component_statuses: The component_statuses of this ServerStatusResponse.  # noqa: E501
        :type: object
        """
        if component_statuses is None:
            raise ValueError("Invalid value for `component_statuses`, must not be `None`")  # noqa: E501

        self._component_statuses = component_statuses

    @property
    def server_status_message(self):
        """Gets the server_status_message of this ServerStatusResponse.  # noqa: E501


        :return: The server_status_message of this ServerStatusResponse.  # noqa: E501
        :rtype: ServerStatusMessage
        """
        return self._server_status_message

    @server_status_message.setter
    def server_status_message(self, server_status_message):
        """Sets the server_status_message of this ServerStatusResponse.


        :param server_status_message: The server_status_message of this ServerStatusResponse.  # noqa: E501
        :type: ServerStatusMessage
        """
        if server_status_message is None:
            raise ValueError("Invalid value for `server_status_message`, must not be `None`")  # noqa: E501

        self._server_status_message = server_status_message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServerStatusResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
