# coding: utf-8

"""
    IncQuery Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.12.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ServerInfoResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'indexer_mode': 'str',
        'persistent_index_mode': 'str'
    }

    attribute_map = {
        'indexer_mode': 'indexerMode',
        'persistent_index_mode': 'persistentIndexMode'
    }

    def __init__(self, indexer_mode=None, persistent_index_mode=None):  # noqa: E501
        """ServerInfoResponse - a model defined in OpenAPI"""  # noqa: E501

        self._indexer_mode = None
        self._persistent_index_mode = None
        self.discriminator = None

        if indexer_mode is not None:
            self.indexer_mode = indexer_mode
        if persistent_index_mode is not None:
            self.persistent_index_mode = persistent_index_mode

    @property
    def indexer_mode(self):
        """Gets the indexer_mode of this ServerInfoResponse.  # noqa: E501


        :return: The indexer_mode of this ServerInfoResponse.  # noqa: E501
        :rtype: str
        """
        return self._indexer_mode

    @indexer_mode.setter
    def indexer_mode(self, indexer_mode):
        """Sets the indexer_mode of this ServerInfoResponse.


        :param indexer_mode: The indexer_mode of this ServerInfoResponse.  # noqa: E501
        :type: str
        """
        allowed_values = ["EMBEDDED", "DISTRIBUTED"]  # noqa: E501
        if indexer_mode not in allowed_values:
            raise ValueError(
                "Invalid value for `indexer_mode` ({0}), must be one of {1}"  # noqa: E501
                .format(indexer_mode, allowed_values)
            )

        self._indexer_mode = indexer_mode

    @property
    def persistent_index_mode(self):
        """Gets the persistent_index_mode of this ServerInfoResponse.  # noqa: E501


        :return: The persistent_index_mode of this ServerInfoResponse.  # noqa: E501
        :rtype: str
        """
        return self._persistent_index_mode

    @persistent_index_mode.setter
    def persistent_index_mode(self, persistent_index_mode):
        """Sets the persistent_index_mode of this ServerInfoResponse.


        :param persistent_index_mode: The persistent_index_mode of this ServerInfoResponse.  # noqa: E501
        :type: str
        """
        allowed_values = ["EMBEDDED", "DISTRIBUTED"]  # noqa: E501
        if persistent_index_mode not in allowed_values:
            raise ValueError(
                "Invalid value for `persistent_index_mode` ({0}), must be one of {1}"  # noqa: E501
                .format(persistent_index_mode, allowed_values)
            )

        self._persistent_index_mode = persistent_index_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServerInfoResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
